--------------------------------------------------------
--  File created - Saturday-March-11-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYÉ
--------------------------------------------------------

  CREATE TABLE "NOURHENE"."EMPLOYÉ" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"POSTE" VARCHAR2(20 BYTE), 
	"SALAIRE" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINANCEMENT
--------------------------------------------------------

  CREATE TABLE "NOURHENE"."FINANCEMENT" 
   (	"ID" NUMBER, 
	"TYPE_FACTURE" VARCHAR2(20 BYTE), 
	"NOM_SERVICE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"LIBELLE" VARCHAR2(20 BYTE), 
	"DATER" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "NOURHENE"."SERVICE" 
   (	"ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"TECHNICIAN" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"DATER" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCKS
--------------------------------------------------------

  CREATE TABLE "NOURHENE"."STOCKS" 
   (	"ID" NUMBER, 
	"LIBELLE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"QUANTITE" NUMBER, 
	"ID_SERVICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into NOURHENE."EMPLOYÉ"
SET DEFINE OFF;
REM INSERTING into NOURHENE.FINANCEMENT
SET DEFINE OFF;
REM INSERTING into NOURHENE.SERVICE
SET DEFINE OFF;
Insert into NOURHENE.SERVICE (ID,DESCRIPTION,TECHNICIAN,PRIX,DATER) values (12,null,null,null,null);
Insert into NOURHENE.SERVICE (ID,DESCRIPTION,TECHNICIAN,PRIX,DATER) values (14,null,null,null,null);
Insert into NOURHENE.SERVICE (ID,DESCRIPTION,TECHNICIAN,PRIX,DATER) values (5,null,null,null,null);
Insert into NOURHENE.SERVICE (ID,DESCRIPTION,TECHNICIAN,PRIX,DATER) values (2,null,null,null,null);
REM INSERTING into NOURHENE.STOCKS
SET DEFINE OFF;
Insert into NOURHENE.STOCKS (ID,LIBELLE,PRIX,QUANTITE,ID_SERVICE) values (15,'nourhene',456,45,45);
Insert into NOURHENE.STOCKS (ID,LIBELLE,PRIX,QUANTITE,ID_SERVICE) values (558,'ergq',756,465,54);
Insert into NOURHENE.STOCKS (ID,LIBELLE,PRIX,QUANTITE,ID_SERVICE) values (846,'iopm',45,56,564);
Insert into NOURHENE.STOCKS (ID,LIBELLE,PRIX,QUANTITE,ID_SERVICE) values (557,'ergq',756,465,54);
Insert into NOURHENE.STOCKS (ID,LIBELLE,PRIX,QUANTITE,ID_SERVICE) values (45,'ryth',75,57,57);
--------------------------------------------------------
--  DDL for Index EMPLOYÉ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOURHENE"."EMPLOYÉ_PK" ON "NOURHENE"."EMPLOYÉ" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SERVICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOURHENE"."SERVICE_PK" ON "NOURHENE"."SERVICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STOCKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOURHENE"."STOCKS_PK" ON "NOURHENE"."STOCKS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FINANCEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOURHENE"."FINANCEMENT_PK" ON "NOURHENE"."FINANCEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STOCKS
--------------------------------------------------------

  ALTER TABLE "NOURHENE"."STOCKS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "NOURHENE"."STOCKS" ADD CONSTRAINT "STOCKS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "NOURHENE"."SERVICE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "NOURHENE"."SERVICE" ADD CONSTRAINT "SERVICE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FINANCEMENT
--------------------------------------------------------

  ALTER TABLE "NOURHENE"."FINANCEMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "NOURHENE"."FINANCEMENT" ADD CONSTRAINT "FINANCEMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYÉ
--------------------------------------------------------

  ALTER TABLE "NOURHENE"."EMPLOYÉ" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "NOURHENE"."EMPLOYÉ" ADD CONSTRAINT "EMPLOYÉ_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
