--------------------------------------------------------
--  File created - Tuesday-December-13-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPARTENIR
--------------------------------------------------------

  CREATE TABLE "YASSINE"."APPARTENIR" 
   (	"ID_VOY" NUMBER, 
	"ID_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BENEFICIER
--------------------------------------------------------

  CREATE TABLE "YASSINE"."BENEFICIER" 
   (	"ID_VOYAGEURS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "YASSINE"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"NUMTEL" VARCHAR2(20 BYTE), 
	"DATECREATION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTENIR
--------------------------------------------------------

  CREATE TABLE "YASSINE"."CONTENIR" 
   (	"FLIGHTREF" VARCHAR2(20 BYTE), 
	"SERVICE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "YASSINE"."EMPLOYEE" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"AGE" NUMBER, 
	"ROLE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"MODE_PASS" VARCHAR2(20 BYTE), 
	"NUM_TEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATIONS
--------------------------------------------------------

  CREATE TABLE "YASSINE"."RESERVATIONS" 
   (	"NOM_SERVICE" VARCHAR2(20 BYTE), 
	"STARTING_DATE" DATE, 
	"ENDING_DATE" DATE, 
	"NB_PERSONNES" VARCHAR2(20 BYTE), 
	"RESERVATION_TYPE" VARCHAR2(20 BYTE), 
	"RESERVATION_PRICE" VARCHAR2(20 BYTE), 
	"RESERVATION_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE "YASSINE"."SERVICES" 
   (	"SERVICE_ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"DISPONIBILITY" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NB_PLACES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPECIFICATIONS
--------------------------------------------------------

  CREATE TABLE "YASSINE"."SPECIFICATIONS" 
   (	"SERVICE_NAME" VARCHAR2(20 BYTE), 
	"SERVICE_SPEC" VARCHAR2(20 BYTE), 
	"NB_PLACES" NUMBER, 
	"PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUPERVISER
--------------------------------------------------------

  CREATE TABLE "YASSINE"."SUPERVISER" 
   (	"CIN_EMP" NUMBER, 
	"CIN_ADMIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VOYAGES
--------------------------------------------------------

  CREATE TABLE "YASSINE"."VOYAGES" 
   (	"FLIGHTREF" VARCHAR2(20 BYTE), 
	"LIEUDEP" VARCHAR2(20 BYTE), 
	"LIEUARR" VARCHAR2(20 BYTE), 
	"DATEDEP" DATE, 
	"DATEARR" DATE, 
	"AIRLINE" VARCHAR2(20 BYTE), 
	"MONTANT" NUMBER, 
	"NBPER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VOYAGEURS
--------------------------------------------------------

  CREATE TABLE "YASSINE"."VOYAGEURS" 
   (	"CIN" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(50 BYTE), 
	"DATE_NAIS" DATE, 
	"GENDER" VARCHAR2(20 BYTE), 
	"PHOTO" BLOB, 
	"ID_CLIENT" NUMBER, 
	"RFID_CARD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into YASSINE.APPARTENIR
SET DEFINE OFF;
REM INSERTING into YASSINE.BENEFICIER
SET DEFINE OFF;
REM INSERTING into YASSINE.CLIENT
SET DEFINE OFF;
Insert into YASSINE.CLIENT (ID_CLIENT,NOM,EMAIL,NUMTEL,DATECREATION) values (1,'Changed','bingodrag21@gmail.com','+21620710182',to_date('14-NOV-22','DD-MON-RR'));
Insert into YASSINE.CLIENT (ID_CLIENT,NOM,EMAIL,NUMTEL,DATECREATION) values (43,'TEST111','mohamedyassinebenmiled@gmail.com','+21650845921',to_date('06-DEC-22','DD-MON-RR'));
Insert into YASSINE.CLIENT (ID_CLIENT,NOM,EMAIL,NUMTEL,DATECREATION) values (3,'Testipp','test@test.com','+21650845921',to_date('15-NOV-21','DD-MON-RR'));
Insert into YASSINE.CLIENT (ID_CLIENT,NOM,EMAIL,NUMTEL,DATECREATION) values (21,'HappySlappyFace','happyslappyface@test.com','+21652869221',to_date('22-NOV-22','DD-MON-RR'));
REM INSERTING into YASSINE.CONTENIR
SET DEFINE OFF;
REM INSERTING into YASSINE.EMPLOYEE
SET DEFINE OFF;
Insert into YASSINE.EMPLOYEE (CIN,NOM,PRENOM,DATE_NAISSANCE,AGE,ROLE,EMAIL,MODE_PASS,NUM_TEL) values (51,'Yassine','BenMiled',to_date('01-JAN-00','DD-MON-RR'),21,'Admin','HELLO@hello.hello','YES','+21650845921');
Insert into YASSINE.EMPLOYEE (CIN,NOM,PRENOM,DATE_NAISSANCE,AGE,ROLE,EMAIL,MODE_PASS,NUM_TEL) values (14510507,'Yassine','BenMiled',to_date('01-JAN-00','DD-MON-RR'),12,'Employe','mohamedyassinebenmiled@gmail.com','Y211195a','+21650845921');
REM INSERTING into YASSINE.RESERVATIONS
SET DEFINE OFF;
REM INSERTING into YASSINE.SERVICES
SET DEFINE OFF;
Insert into YASSINE.SERVICES (SERVICE_ID,NOM,DISPONIBILITY,TYPE,NB_PLACES) values (1,'Janjoun','available','Ma5me5',4);
REM INSERTING into YASSINE.SPECIFICATIONS
SET DEFINE OFF;
REM INSERTING into YASSINE.SUPERVISER
SET DEFINE OFF;
Insert into YASSINE.SUPERVISER (CIN_EMP,CIN_ADMIN) values (14510507,51);
REM INSERTING into YASSINE.VOYAGES
SET DEFINE OFF;
Insert into YASSINE.VOYAGES (FLIGHTREF,LIEUDEP,LIEUARR,DATEDEP,DATEARR,AIRLINE,MONTANT,NBPER) values ('123','Tunisia','France',to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),'Tunisair',150,4);
Insert into YASSINE.VOYAGES (FLIGHTREF,LIEUDEP,LIEUARR,DATEDEP,DATEARR,AIRLINE,MONTANT,NBPER) values ('3','France','United Kingdom',to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),'Tunisair',3,88);
Insert into YASSINE.VOYAGES (FLIGHTREF,LIEUDEP,LIEUARR,DATEDEP,DATEARR,AIRLINE,MONTANT,NBPER) values ('5','Tunisia','Tunisia',to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),'Tunisair',3,88);
Insert into YASSINE.VOYAGES (FLIGHTREF,LIEUDEP,LIEUARR,DATEDEP,DATEARR,AIRLINE,MONTANT,NBPER) values ('9','France','United Kingdom',to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),'Tunisair',8.5,77);
REM INSERTING into YASSINE.VOYAGEURS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index APPARTENIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."APPARTENIR_PK" ON "YASSINE"."APPARTENIR" ("ID_CLIENT", "ID_VOY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BENEFICIER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."BENEFICIER_PK" ON "YASSINE"."BENEFICIER" ("ID_VOYAGEURS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."CLIENT_PK" ON "YASSINE"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."UNIQUE_EMAIL" ON "YASSINE"."CLIENT" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONTENIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."CONTENIR_PK" ON "YASSINE"."CONTENIR" ("FLIGHTREF", "SERVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."EMPLOYE_PK" ON "YASSINE"."EMPLOYEE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."RESERVATIONS_PK" ON "YASSINE"."RESERVATIONS" ("RESERVATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SERVICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."SERVICES_PK" ON "YASSINE"."SERVICES" ("SERVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPECIFICATIONS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."SPECIFICATIONS_UK1" ON "YASSINE"."SPECIFICATIONS" ("SERVICE_SPEC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUPERVISER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."SUPERVISER_PK" ON "YASSINE"."SUPERVISER" ("CIN_EMP", "CIN_ADMIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VOYAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."VOYAGES_PK" ON "YASSINE"."VOYAGES" ("FLIGHTREF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VOYAGEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."VOYAGEURS_PK" ON "YASSINE"."VOYAGEURS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CLIENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "YASSINE"."CLIENT_TRG" 
BEFORE INSERT ON CLIENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CLIENT IS NULL THEN
      SELECT CLIENT_SEQ.NEXTVAL INTO :NEW.ID_CLIENT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "YASSINE"."CLIENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RESERVATIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "YASSINE"."RESERVATIONS_TRG" 
BEFORE INSERT ON RESERVATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.RESERVATION_ID IS NULL THEN
      SELECT RESERVATIONS_SEQ.NEXTVAL INTO :NEW.RESERVATION_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "YASSINE"."RESERVATIONS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table APPARTENIR
--------------------------------------------------------

  ALTER TABLE "YASSINE"."APPARTENIR" ADD CONSTRAINT "APPARTENIR_PK" PRIMARY KEY ("ID_CLIENT", "ID_VOY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."APPARTENIR" MODIFY ("ID_VOY" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."APPARTENIR" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BENEFICIER
--------------------------------------------------------

  ALTER TABLE "YASSINE"."BENEFICIER" ADD CONSTRAINT "BENEFICIER_PK" PRIMARY KEY ("ID_VOYAGEURS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."BENEFICIER" MODIFY ("ID_VOYAGEURS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "YASSINE"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."CLIENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."CLIENT" ADD CONSTRAINT "UNIQUE_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTENIR
--------------------------------------------------------

  ALTER TABLE "YASSINE"."CONTENIR" ADD CONSTRAINT "CONTENIR_PK" PRIMARY KEY ("FLIGHTREF", "SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."CONTENIR" MODIFY ("FLIGHTREF" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."CONTENIR" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "YASSINE"."EMPLOYEE" MODIFY ("MODE_PASS" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."EMPLOYEE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."EMPLOYEE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."EMPLOYEE" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATIONS
--------------------------------------------------------

  ALTER TABLE "YASSINE"."RESERVATIONS" MODIFY ("NOM_SERVICE" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."RESERVATIONS" MODIFY ("RESERVATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."RESERVATIONS" MODIFY ("RESERVATION_ID" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."RESERVATIONS" ADD CONSTRAINT "RESERVATIONS_PK" PRIMARY KEY ("RESERVATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "YASSINE"."SERVICES" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."SERVICES" ADD CONSTRAINT "SERVICES_PK" PRIMARY KEY ("SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPECIFICATIONS
--------------------------------------------------------

  ALTER TABLE "YASSINE"."SPECIFICATIONS" MODIFY ("SERVICE_SPEC" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."SPECIFICATIONS" ADD CONSTRAINT "SPECIFICATIONS_UK1" UNIQUE ("SERVICE_SPEC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUPERVISER
--------------------------------------------------------

  ALTER TABLE "YASSINE"."SUPERVISER" ADD CONSTRAINT "SUPERVISER_PK" PRIMARY KEY ("CIN_EMP", "CIN_ADMIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."SUPERVISER" MODIFY ("CIN_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."SUPERVISER" MODIFY ("CIN_EMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOYAGES
--------------------------------------------------------

  ALTER TABLE "YASSINE"."VOYAGES" ADD CONSTRAINT "VOYAGES_PK" PRIMARY KEY ("FLIGHTREF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."VOYAGES" MODIFY ("FLIGHTREF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOYAGEURS
--------------------------------------------------------

  ALTER TABLE "YASSINE"."VOYAGEURS" ADD CONSTRAINT "VOYAGEURS_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."VOYAGEURS" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APPARTENIR
--------------------------------------------------------

  ALTER TABLE "YASSINE"."APPARTENIR" ADD CONSTRAINT "APPARTENIR_FK1" FOREIGN KEY ("ID_VOY")
	  REFERENCES "YASSINE"."VOYAGEURS" ("CIN") ENABLE;
  ALTER TABLE "YASSINE"."APPARTENIR" ADD CONSTRAINT "APPARTENIR_FK2" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "YASSINE"."CLIENT" ("ID_CLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BENEFICIER
--------------------------------------------------------

  ALTER TABLE "YASSINE"."BENEFICIER" ADD CONSTRAINT "BENEFICIER_FK2" FOREIGN KEY ("ID_VOYAGEURS")
	  REFERENCES "YASSINE"."VOYAGEURS" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTENIR
--------------------------------------------------------

  ALTER TABLE "YASSINE"."CONTENIR" ADD CONSTRAINT "CONTENIR_FK2" FOREIGN KEY ("FLIGHTREF")
	  REFERENCES "YASSINE"."VOYAGES" ("FLIGHTREF") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUPERVISER
--------------------------------------------------------

  ALTER TABLE "YASSINE"."SUPERVISER" ADD CONSTRAINT "SUPERVISER_FK1" FOREIGN KEY ("CIN_EMP")
	  REFERENCES "YASSINE"."EMPLOYEE" ("CIN") ENABLE;
  ALTER TABLE "YASSINE"."SUPERVISER" ADD CONSTRAINT "SUPERVISER_FK2" FOREIGN KEY ("CIN_ADMIN")
	  REFERENCES "YASSINE"."EMPLOYEE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOYAGEURS
--------------------------------------------------------

  ALTER TABLE "YASSINE"."VOYAGEURS" ADD CONSTRAINT "VOYAGEURS_FK1" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "YASSINE"."CLIENT" ("ID_CLIENT") ON DELETE SET NULL ENABLE;
